service: 'virtual-wallet-lambda'

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  vpc:
    securityGroupIds:
      - sg-???
    subnetIds:
      - subnet-???
  environment:
    # DB_CONNECTION: 'rds_iam'
    SECRET_ID: '???'
    # DB_HOST: '???.rds.amazonaws.com'
    # DB_PORT: 3306
    # DB_USERNAME: k_kojima_wallet
    DB_DATABASE: 'k_kojima_lambda_test'
    LOG_CHANNEL: 'stderr'
    APP_ENV: 'production'
    APP_KEY: 'base64:???'
  ecr:
    images:
      virtual-wallet-kk:
        path: ./
        file: 'docker/Dockerfile'
        buildArgs:
          { }

plugins:
  - ./vendor/bref/bref

package:
  # Files and directories to exclude from deployment
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'
    - '!.idea/**'
    - '!.github/**'
    - '!.env*'

functions:
  main:
    # handler: public/index.php
    # Provided by plugin
    # noinspection YAMLSchemaValidation
    # runtime: php-81-fpm
    url:
      authorizer: aws_iam
    image:
      name: virtual-wallet-kk
    timeout: 90
#  artisan:
#    handler: artisan
#    # Provided by plugin
#    # noinspection YAMLSchemaValidation
#    runtime: php-81-console
#    timeout: 720
