name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@baf9535ba58ae8ac3a7362d932ca85fc38621a5d
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Get GID
      run: |
        echo "WWWGROUP=$(id -g)" >> $GITHUB_ENV
        echo "WWWUSER=$(id -u)" >> $GITHUB_ENV
    - name: Prebuild image
      uses: docker/build-push-action@v4
      with:
        # Copied from docker-compose.yml
        context: ./vendor/laravel/sail/runtimes/8.2
        load: true
        tags: sail-8.2/app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          WWWGROUP=${{ env.WWWGROUP }}
    - name: Sail Up
      run: ./vendor/bin/sail up -d
    - name: Check containers
      run: docker compose ps
    - name: Migration DB
      run: ./vendor/bin/sail php artisan migrate:fresh --seed
    - name: Test
      run: ./vendor/bin/sail test
    - name: Sail down
      if: always()
      run: ./vendor/bin/sail down

  dusk:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: dusk_test_db
      DB_USERNAME: root
      DB_PASSWORD: root
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v4
      - run: sudo systemctl start mysql.service
      - run: mysql --user="root" --password="root" -e "CREATE DATABASE dusk_test_db;"
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver --detect
      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &
      - name: Run Laravel Server
        run: php artisan serve --no-reload --host=localhost --port=8000 &
      - name: Migrate
        run: php artisan migrate:fresh --seed
      - name: Run test
        run: php artisan dusk
        env:
          APP_URL: 'http://localhost:8000'
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: virtual-wallet-screenshots-${{ github.run_number }}
          path: tests/Browser/screenshots
          if-no-files-found: ignore
